### ISSUE TITLE
Error running autoInstallPackage

### ISSUE THREAD

**Issue by bethpet** [Adobe-Marketing-Cloud/aem-sample-we-retail#145] opened 2017-12-30 13:01 UTC
Hello,
   I trying to configure We Retail to use in my local environment, but when I run the autoInstallPackage, I keep having this same error below, do you know what this is?

[ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.12:check (default) on project we.retail.config: Too many files with unapproved license: 1 See RAT report in: C:\AEM 6.3 - Quickstart\projeto eclipse\aem-sample-we-retail-master\config\target\rat.txt -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.rat:apache-rat-plugin:0.12:check (default) on project we.retail.config: Too many files with unapproved license: 1 See RAT report in: C:\AEM 6.3 - Quickstart\projeto eclipse\aem-sample-we-retail-master\config\target\rat.txt
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.rat.mp.RatCheckException: Too many files with unapproved license: 1 See RAT report in: C:\AEM 6.3 - Quickstart\projeto eclipse\aem-sample-we-retail-master\config\target\rat.txt
	at org.apache.rat.mp.RatCheckMojo.check(RatCheckMojo.java:183)
	at org.apache.rat.mp.RatCheckMojo.execute(RatCheckMojo.java:156)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :we.retail.config
Picked up _JAVA_OPTIONS: -Xmx512M

thanks in advance.

**Comment by gknob** [comment] 2017-12-30 14:50
This can be due to some files related to your IDE configuration.
Still, the issue seems to be there in other modules too.

As a workaround, please run your command with `-Drat.skip`, this will skip the Apache RAT plugin execution.

**Comment by bpauli** [comment] 2018-03-06 19:27
@bethpet I'm closing this issue as it is not reproducible on my build. If you're still facing this issue please provide output of the file `C:\AEM 6.3 - Quickstart\projeto eclipse\aem-sample-we-retail-master\config\target\rat.txt`

**Closed by bpauli** 2018-03-06 19:27 UTC

**Comment by bsagarneel** [comment] 2018-07-09 07:18
[rat.txt](https://github.com/Adobe-Marketing-Cloud/aem-sample-we-retail/files/2174960/rat.txt)
Hi,

Please find the rat file attached. 

I am getting the same error. 

### _[ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.12:check (default) on project we.retail.config: Too many files with unapproved license: 1 See RAT report in: /Users/sbiswas/Dev/Code/aem-sample-we-retail/config/target/rat.txt -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.rat:apache-rat-plugin:0.12:check (default) on project we.retail.config: Too many files with unapproved license: 1 See RAT report in: /Users/sbiswas/Dev/Code/aem-sample-we-retail/config/target/rat.txt
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)_

**Comment by rajramo61** [comment] 2018-12-05 02:21
I saw this error with intellij ide. I just added one more entry to excludes list of
apache-rat-plugin and it worked like charm

<exclude>**/*.iml</exclude>
